#ifndef __CONFIGURATION__
#define __CONFIGTUATION__

#include<string>
#include <map>
class HourglassConfiguration{
 public:
  std::string this_name;
  HourglassConfiguration();
  ~HourglassConfiguration();
  int GenerateEmptyConfigFile();
  
  //  LoadConfigFile:
  // no checking is done to see if all config parameters are present, so
  // partial files may be loaded to enable mutliple sources to generate config
  // parameters.
  int LoadConfigFile(const std::string& in_file_name); 
  
  int ModifyConfigParameter(const std::string& param, const std::string& val);
  int SaveConfigFile(const std::string& out_dir);
  int ShowConfigFile();
  int SetDefaultValues();

  // BatchCreateConfigFiles
  // This member creates all the configuration files neccessary for simulating
  // the vertex profile of each individual scan step. Because of the nature of
  // the vernier scan, we take data for scanned steps sequentially, therefore,
  // files zdc_counts_per_step_file, x_offsets_file and y_offsets_file contain
  // configuration parameters for several steps. Beam widths are handled with
  // the h_width_file and v_width file (h = horizontal, v = vertical), and beam
  // populations for the blue and yellow beams are stored in
  // beam_population_file.
  //
  // In summary, we give this class configuration information for all the data
  // sources from a single vernier scan, which are automatically generated by
  // classes which work with that data.
  //
  // WcmDcctManager : creates beam_population_file
  // HourglassData  : creates zdc_counts_per_step_file 
  // BeamWidthTime  : creates [xy]_offsets_file, [hv]_width_file
  int BatchCreateConfigFiles(
    const std::string& run_number_,
    const std::string& zdc_counts_per_step_file,
    const std::string& x_offsets_file,
    const std::string& y_offsets_file,
    const std::string& h_width_file,
    const std::string& v_width_file,
    const std::string& beam_population_file, 
    const std::string& sim_config_out_dir
  );

  // Generate a unique config file name from identifying information
  std::string GetConfigName();

  // returns true if par is found to be a parameter in config_. Designed usage
  // is for checking input when loading partial parameter lists from files.
  bool ParameterExists(const std::string& par);

 private:
  std::map<std::string,std::string> config_;
  /** config_: maps config parameter to config value. Conversion handled with
   * stringstreams. */
};

#endif
