all:
	g++ -std=c++0x MakeSimultaneousDistributions.C `root-config --libs` -I `root-config --incdir` -o make_simultaneous_distribution.exe
clean:
	rm -rf make_simultaneous_distribution.exe
	rm -rf *.root
